export type OnboardingFlowName =
  | 'paint_miniature'
  | 'organize_hobby'
  | 'create_content'

export type OnboardingActionDefinition = {
  flowName: OnboardingFlowName
  milestoneKey: string
  milestoneLabel: string
  milestoneOrder: number
  actionKey: string
  actionLabel: string
  actionOrder: number
  breadcrumb: string
  refPage: string
  refComponent: string
}

export const onboardingFlowDefinitions = [
  {
    name: 'paint_miniature',
    title: 'Paint My Next Miniature',
    personaLabel: 'Painter',
    description:
      'Set up a miniature, prepare a painting plan, paint it using Obsidian Gallery, and leave your next session ready to resume.',
  },
  {
    name: 'organize_hobby',
    title: 'Sort Out My Hobby',
    personaLabel: 'Hobby Organizer',
    description:
      'Organize current projects, active miniatures and paints, then establish a repeatable Painting Table workflow.',
  },
  {
    name: 'create_content',
    title: 'Write a Guide',
    personaLabel: 'Guide Creator',
    description:
      'Turn painting knowledge into structured Cards and Decks, preview the experience, and complete your first Guide.',
  },
] as const

export const onboardingActionDefinitions: OnboardingActionDefinition[] = [
  {
    flowName: 'paint_miniature',
    milestoneKey: 'setup_miniature',
    milestoneLabel: 'Set up your miniature',
    milestoneOrder: 1,
    actionKey: 'create_unit',
    actionLabel: 'Create a Unit',
    actionOrder: 1,
    breadcrumb: 'Units -> + New Unit',
    refPage: 'units',
    refComponent: 'create_unit',
  },
  {
    flowName: 'paint_miniature',
    milestoneKey: 'setup_miniature',
    milestoneLabel: 'Set up your miniature',
    milestoneOrder: 1,
    actionKey: 'name_unit',
    actionLabel: 'Give your Unit a name',
    actionOrder: 2,
    breadcrumb: 'Unit Builder -> Info -> Name',
    refPage: 'unit_builder',
    refComponent: 'unit_name',
  },
  {
    flowName: 'paint_miniature',
    milestoneKey: 'setup_miniature',
    milestoneLabel: 'Set up your miniature',
    milestoneOrder: 1,
    actionKey: 'add_unit_image',
    actionLabel: 'Add an image of your miniature',
    actionOrder: 3,
    breadcrumb: 'Unit Builder -> Image -> Upload or choose effigy',
    refPage: 'unit_builder',
    refComponent: 'unit_image',
  },
  {
    flowName: 'paint_miniature',
    milestoneKey: 'setup_miniature',
    milestoneLabel: 'Set up your miniature',
    milestoneOrder: 1,
    actionKey: 'complete_unit_info',
    actionLabel: "Fill in your miniature's details",
    actionOrder: 4,
    breadcrumb: 'Unit Builder -> Info -> Details',
    refPage: 'unit_builder',
    refComponent: 'unit_info',
  },
  {
    flowName: 'paint_miniature',
    milestoneKey: 'setup_miniature',
    milestoneLabel: 'Set up your miniature',
    milestoneOrder: 1,
    actionKey: 'set_unit_progress_stage',
    actionLabel: 'Tell us where you are in the painting process',
    actionOrder: 5,
    breadcrumb: 'Unit -> Progress -> Current Stage',
    refPage: 'unit_detail',
    refComponent: 'progress_stage',
  },
  {
    flowName: 'paint_miniature',
    milestoneKey: 'prepare_to_paint',
    milestoneLabel: 'Prepare to paint',
    milestoneOrder: 2,
    actionKey: 'choose_unit_guide',
    actionLabel: 'Choose a Guide to follow',
    actionOrder: 6,
    breadcrumb: 'Unit -> Guide -> Choose Guide',
    refPage: 'unit_detail',
    refComponent: 'guide_picker',
  },
  {
    flowName: 'paint_miniature',
    milestoneKey: 'prepare_to_paint',
    milestoneLabel: 'Prepare to paint',
    milestoneOrder: 2,
    actionKey: 'assign_guide_to_unit',
    actionLabel: 'Add the Guide to your Unit',
    actionOrder: 7,
    breadcrumb: 'Guide -> Use this Guide -> Select Unit',
    refPage: 'guide_detail',
    refComponent: 'assign_guide',
  },
  {
    flowName: 'paint_miniature',
    milestoneKey: 'prepare_to_paint',
    milestoneLabel: 'Prepare to paint',
    milestoneOrder: 2,
    actionKey: 'add_unit_paints',
    actionLabel: 'Add the paints you plan to use',
    actionOrder: 8,
    breadcrumb: 'Unit -> Colors -> Add Paint',
    refPage: 'unit_detail',
    refComponent: 'unit_palette',
  },
  {
    flowName: 'paint_miniature',
    milestoneKey: 'prepare_to_paint',
    milestoneLabel: 'Prepare to paint',
    milestoneOrder: 2,
    actionKey: 'mark_paints_owned',
    actionLabel: 'Mark the paints you already have',
    actionOrder: 9,
    breadcrumb: 'Paint -> Ownership -> Owned',
    refPage: 'paint_detail',
    refComponent: 'paint_ownership',
  },
  {
    flowName: 'paint_miniature',
    milestoneKey: 'prepare_to_paint',
    milestoneLabel: 'Prepare to paint',
    milestoneOrder: 2,
    actionKey: 'set_first_session_goal',
    actionLabel: "Decide what you'll paint first",
    actionOrder: 10,
    breadcrumb: 'Unit -> Sessions -> Session Goal',
    refPage: 'unit_detail',
    refComponent: 'session_goal',
  },
  {
    flowName: 'paint_miniature',
    milestoneKey: 'paint_with_app',
    milestoneLabel: 'Paint with the app',
    milestoneOrder: 3,
    actionKey: 'start_first_session',
    actionLabel: 'Start your first painting session',
    actionOrder: 11,
    breadcrumb: 'Unit -> Session -> Start Session',
    refPage: 'unit_detail',
    refComponent: 'session_tracker',
  },
  {
    flowName: 'paint_miniature',
    milestoneKey: 'paint_with_app',
    milestoneLabel: 'Paint with the app',
    milestoneOrder: 3,
    actionKey: 'finish_first_session',
    actionLabel: 'Finish your painting session',
    actionOrder: 12,
    breadcrumb: 'Active Session -> Finish Session',
    refPage: 'active_session',
    refComponent: 'finish_session',
  },
  {
    flowName: 'paint_miniature',
    milestoneKey: 'leave_handoff',
    milestoneLabel: 'Leave a handoff',
    milestoneOrder: 4,
    actionKey: 'add_session_progress_photo',
    actionLabel: 'Add a photo of your progress',
    actionOrder: 13,
    breadcrumb: 'Session Summary -> Progress Photo -> Add Photo',
    refPage: 'session_summary',
    refComponent: 'progress_photo',
  },
  {
    flowName: 'paint_miniature',
    milestoneKey: 'leave_handoff',
    milestoneLabel: 'Leave a handoff',
    milestoneOrder: 4,
    actionKey: 'record_session_paints',
    actionLabel: 'Record the paints you used',
    actionOrder: 14,
    breadcrumb: 'Session Summary -> Paints Used -> Add Paints',
    refPage: 'session_summary',
    refComponent: 'session_paints',
  },
  {
    flowName: 'paint_miniature',
    milestoneKey: 'leave_handoff',
    milestoneLabel: 'Leave a handoff',
    milestoneOrder: 4,
    actionKey: 'record_session_note',
    actionLabel: 'Leave yourself a painting note',
    actionOrder: 15,
    breadcrumb: 'Session Summary -> Notes -> Add Note',
    refPage: 'session_summary',
    refComponent: 'session_notes',
  },
  {
    flowName: 'paint_miniature',
    milestoneKey: 'leave_handoff',
    milestoneLabel: 'Leave a handoff',
    milestoneOrder: 4,
    actionKey: 'set_next_painting_action',
    actionLabel: "Decide what you'll do next",
    actionOrder: 16,
    breadcrumb: 'Session Summary -> Next Action -> Save',
    refPage: 'session_summary',
    refComponent: 'next_action',
  },
  {
    flowName: 'organize_hobby',
    milestoneKey: 'map_hobby',
    milestoneLabel: 'Map your hobby',
    milestoneOrder: 1,
    actionKey: 'create_project',
    actionLabel: 'Create a Project',
    actionOrder: 1,
    breadcrumb: 'Projects -> + New Project',
    refPage: 'projects',
    refComponent: 'create_project',
  },
  {
    flowName: 'organize_hobby',
    milestoneKey: 'map_hobby',
    milestoneLabel: 'Map your hobby',
    milestoneOrder: 1,
    actionKey: 'add_project_unit',
    actionLabel: "Add something you're currently painting",
    actionOrder: 2,
    breadcrumb: 'Project -> Units -> + Add Unit',
    refPage: 'project_detail',
    refComponent: 'add_unit',
  },
  {
    flowName: 'organize_hobby',
    milestoneKey: 'map_hobby',
    milestoneLabel: 'Map your hobby',
    milestoneOrder: 1,
    actionKey: 'set_unit_status',
    actionLabel: 'Decide where this Unit belongs',
    actionOrder: 3,
    breadcrumb: 'Unit -> Overview -> Status',
    refPage: 'unit_detail',
    refComponent: 'unit_status',
  },
  {
    flowName: 'organize_hobby',
    milestoneKey: 'map_hobby',
    milestoneLabel: 'Map your hobby',
    milestoneOrder: 1,
    actionKey: 'organize_set_progress_stage',
    actionLabel: 'Mark where you left off',
    actionOrder: 4,
    breadcrumb: 'Unit -> Progress -> Current Stage',
    refPage: 'unit_detail',
    refComponent: 'progress_stage',
  },
  {
    flowName: 'organize_hobby',
    milestoneKey: 'map_hobby',
    milestoneLabel: 'Map your hobby',
    milestoneOrder: 1,
    actionKey: 'add_unit_to_active_bench',
    actionLabel: 'Put a Unit on your Active Bench',
    actionOrder: 5,
    breadcrumb: 'Unit -> Overview -> Status -> Bench',
    refPage: 'unit_detail',
    refComponent: 'unit_status',
  },
  {
    flowName: 'organize_hobby',
    milestoneKey: 'map_hobby',
    milestoneLabel: 'Map your hobby',
    milestoneOrder: 1,
    actionKey: 'feature_unit',
    actionLabel: 'Choose what deserves your attention first',
    actionOrder: 6,
    breadcrumb: 'Unit -> Overview -> Featured -> On',
    refPage: 'unit_detail',
    refComponent: 'featured_toggle',
  },
  {
    flowName: 'organize_hobby',
    milestoneKey: 'sort_paints',
    milestoneLabel: 'Sort your paints',
    milestoneOrder: 2,
    actionKey: 'add_owned_paints',
    actionLabel: 'Add some paints from your collection',
    actionOrder: 7,
    breadcrumb: 'Vault -> My Collection -> Add Paints',
    refPage: 'vault',
    refComponent: 'paint_collection',
  },
  {
    flowName: 'organize_hobby',
    milestoneKey: 'sort_paints',
    milestoneLabel: 'Sort your paints',
    milestoneOrder: 2,
    actionKey: 'create_project_palette',
    actionLabel: 'Build a palette for your Project',
    actionOrder: 8,
    breadcrumb: 'Project -> Project Palette -> Add Paints',
    refPage: 'project_detail',
    refComponent: 'project_palette',
  },
  {
    flowName: 'organize_hobby',
    milestoneKey: 'sort_paints',
    milestoneLabel: 'Sort your paints',
    milestoneOrder: 2,
    actionKey: 'use_project_palette',
    actionLabel: 'Use your Project palette on a Unit',
    actionOrder: 9,
    breadcrumb: 'Unit -> Colors -> Project Palette -> Use Paint',
    refPage: 'unit_detail',
    refComponent: 'unit_palette',
  },
  {
    flowName: 'organize_hobby',
    milestoneKey: 'establish_hobby_loop',
    milestoneLabel: 'Establish your working loop',
    milestoneOrder: 3,
    actionKey: 'organize_set_next_action',
    actionLabel: "Decide the next thing you'll do",
    actionOrder: 10,
    breadcrumb: 'Featured Unit -> Next Action -> Edit',
    refPage: 'unit_detail',
    refComponent: 'next_action',
  },
  {
    flowName: 'organize_hobby',
    milestoneKey: 'establish_hobby_loop',
    milestoneLabel: 'Establish your working loop',
    milestoneOrder: 3,
    actionKey: 'start_session_from_dashboard',
    actionLabel: 'Start a session from your Painting Table',
    actionOrder: 11,
    breadcrumb: 'Painting Table -> Featured Unit -> Start Session',
    refPage: 'dashboard',
    refComponent: 'featured_unit',
  },
  {
    flowName: 'organize_hobby',
    milestoneKey: 'establish_hobby_loop',
    milestoneLabel: 'Establish your working loop',
    milestoneOrder: 3,
    actionKey: 'organize_finish_session',
    actionLabel: 'Finish the painting session',
    actionOrder: 12,
    breadcrumb: 'Active Session -> Finish Session',
    refPage: 'active_session',
    refComponent: 'finish_session',
  },
  {
    flowName: 'organize_hobby',
    milestoneKey: 'establish_hobby_loop',
    milestoneLabel: 'Establish your working loop',
    milestoneOrder: 3,
    actionKey: 'update_unit_progress',
    actionLabel: 'Update your progress',
    actionOrder: 13,
    breadcrumb: 'Unit -> Progress -> Mark Progress',
    refPage: 'unit_detail',
    refComponent: 'progress_stage',
  },
  {
    flowName: 'organize_hobby',
    milestoneKey: 'establish_hobby_loop',
    milestoneLabel: 'Establish your working loop',
    milestoneOrder: 3,
    actionKey: 'organize_set_followup_action',
    actionLabel: 'Leave your next task ready',
    actionOrder: 14,
    breadcrumb: 'Session Summary -> Next Action -> Save',
    refPage: 'session_summary',
    refComponent: 'next_action',
  },
  {
    flowName: 'create_content',
    milestoneKey: 'start_guide',
    milestoneLabel: 'Start the Guide',
    milestoneOrder: 1,
    actionKey: 'choose_guide_source',
    actionLabel: 'Choose how to start your Guide',
    actionOrder: 1,
    breadcrumb: 'Guides -> + -> Guide Forge -> Choose Source',
    refPage: 'guide_forge',
    refComponent: 'source_picker',
  },
  {
    flowName: 'create_content',
    milestoneKey: 'start_guide',
    milestoneLabel: 'Start the Guide',
    milestoneOrder: 1,
    actionKey: 'create_guide',
    actionLabel: 'Create your Guide',
    actionOrder: 2,
    breadcrumb: 'Guide Forge -> Create Guide',
    refPage: 'guide_forge',
    refComponent: 'create_guide',
  },
  {
    flowName: 'create_content',
    milestoneKey: 'start_guide',
    milestoneLabel: 'Start the Guide',
    milestoneOrder: 1,
    actionKey: 'name_guide',
    actionLabel: 'Give your Guide a title',
    actionOrder: 3,
    breadcrumb: 'Guide Builder -> Info -> Title',
    refPage: 'guide_builder',
    refComponent: 'guide_title',
  },
  {
    flowName: 'create_content',
    milestoneKey: 'start_guide',
    milestoneLabel: 'Start the Guide',
    milestoneOrder: 1,
    actionKey: 'add_guide_cover',
    actionLabel: 'Add a cover image',
    actionOrder: 4,
    breadcrumb: 'Guide Builder -> Cover -> Image',
    refPage: 'guide_builder',
    refComponent: 'guide_cover',
  },
  {
    flowName: 'create_content',
    milestoneKey: 'build_instructions',
    milestoneLabel: 'Build the painting instructions',
    milestoneOrder: 2,
    actionKey: 'name_first_guide_deck',
    actionLabel: 'Name your first Deck',
    actionOrder: 5,
    breadcrumb: 'Guide Builder -> Decks -> First Deck',
    refPage: 'guide_builder',
    refComponent: 'deck_builder',
  },
  {
    flowName: 'create_content',
    milestoneKey: 'build_instructions',
    milestoneLabel: 'Build the painting instructions',
    milestoneOrder: 2,
    actionKey: 'create_step_card',
    actionLabel: 'Add your first painting step',
    actionOrder: 6,
    breadcrumb: 'Guide Builder -> Deck -> + Card -> Step',
    refPage: 'guide_builder',
    refComponent: 'step_card',
  },
  {
    flowName: 'create_content',
    milestoneKey: 'build_instructions',
    milestoneLabel: 'Build the painting instructions',
    milestoneOrder: 2,
    actionKey: 'add_step_paints',
    actionLabel: 'Add the paints used in this step',
    actionOrder: 7,
    breadcrumb: 'Step Card -> Paints -> Add Paint',
    refPage: 'guide_builder',
    refComponent: 'card_paints',
  },
  {
    flowName: 'create_content',
    milestoneKey: 'build_instructions',
    milestoneLabel: 'Build the painting instructions',
    milestoneOrder: 2,
    actionKey: 'add_step_image',
    actionLabel: 'Show what this step looks like',
    actionOrder: 8,
    breadcrumb: 'Step Card -> Image -> Add Image',
    refPage: 'guide_builder',
    refComponent: 'card_image',
  },
  {
    flowName: 'create_content',
    milestoneKey: 'build_instructions',
    milestoneLabel: 'Build the painting instructions',
    milestoneOrder: 2,
    actionKey: 'add_second_guide_card',
    actionLabel: 'Add another Card',
    actionOrder: 9,
    breadcrumb: 'Guide Builder -> Deck -> + Add Card',
    refPage: 'guide_builder',
    refComponent: 'card_picker',
  },
  {
    flowName: 'create_content',
    milestoneKey: 'build_instructions',
    milestoneLabel: 'Build the painting instructions',
    milestoneOrder: 2,
    actionKey: 'reorder_guide_cards',
    actionLabel: 'Put your Guide in the right order',
    actionOrder: 10,
    breadcrumb: 'Guide Builder -> Deck -> Reorder Cards',
    refPage: 'guide_builder',
    refComponent: 'card_order',
  },
  {
    flowName: 'create_content',
    milestoneKey: 'finish_guide',
    milestoneLabel: 'Finish the Guide',
    milestoneOrder: 3,
    actionKey: 'preview_guide',
    actionLabel: 'Preview your Guide as a painter',
    actionOrder: 11,
    breadcrumb: 'Guide Builder -> Preview',
    refPage: 'guide_builder',
    refComponent: 'guide_preview',
  },
  {
    flowName: 'create_content',
    milestoneKey: 'finish_guide',
    milestoneLabel: 'Finish the Guide',
    milestoneOrder: 3,
    actionKey: 'set_guide_visibility',
    actionLabel: 'Choose who can see your Guide',
    actionOrder: 12,
    breadcrumb: 'Guide -> Publish Settings -> Visibility',
    refPage: 'guide_detail',
    refComponent: 'visibility_control',
  },
  {
    flowName: 'create_content',
    milestoneKey: 'finish_guide',
    milestoneLabel: 'Finish the Guide',
    milestoneOrder: 3,
    actionKey: 'finish_first_guide',
    actionLabel: 'Save or publish your Guide',
    actionOrder: 13,
    breadcrumb: 'Guide -> Publish Settings -> Save / Publish',
    refPage: 'guide_detail',
    refComponent: 'publish_control',
  },
]
