create table if not exists public.feature_guide (
  uid text primary key,
  feature_name text not null,
  feature_type text not null,
  location_reference text not null,
  page_path text not null,
  component_reference text,
  explanation text not null,
  place_in_page text not null,
  coach_mark_target text,
  coach_mark_area text not null,
  popup_placement text not null default 'auto',
  display_order integer not null default 0,
  tags text[] not null default '{}',
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint feature_guide_feature_type_check check (
    feature_type in (
      'page',
      'navigation',
      'button',
      'toggle',
      'tab',
      'panel',
      'card',
      'form',
      'modal',
      'workflow',
      'search',
      'filter',
      'export',
      'status',
      'setting'
    )
  )
);

create index if not exists feature_guide_page_path_idx
  on public.feature_guide (page_path, display_order);

create index if not exists feature_guide_feature_type_idx
  on public.feature_guide (feature_type);

create index if not exists feature_guide_tags_idx
  on public.feature_guide using gin (tags);

create or replace function public.set_feature_guide_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists feature_guide_set_updated_at on public.feature_guide;
create trigger feature_guide_set_updated_at
before update on public.feature_guide
for each row execute function public.set_feature_guide_updated_at();

alter table public.feature_guide enable row level security;

drop policy if exists "Feature guide entries are readable" on public.feature_guide;
create policy "Feature guide entries are readable"
on public.feature_guide
for select
using (true);

grant select on public.feature_guide to anon, authenticated;

with seed (
  uid,
  feature_name,
  feature_type,
  location_reference,
  page_path,
  component_reference,
  explanation,
  place_in_page,
  coach_mark_target,
  coach_mark_area,
  popup_placement,
  display_order,
  tags
) as (
  values
    (
      'global.mobile_nav.dashboard',
      'Dashboard navigation',
      'navigation',
      'Global mobile nav > Home',
      '/dashboard',
      'app/components/MobileNav.tsx',
      'Opens the main dashboard, where active units, next actions, progress, and shortcuts are gathered into one check-in screen.',
      'Fixed bottom navigation bar',
      'nav item named Home',
      'The Home icon and label in the bottom navigation',
      'top',
      10,
      array['global', 'navigation', 'dashboard']
    ),
    (
      'global.mobile_nav.projects',
      'Projects navigation',
      'navigation',
      'Global mobile nav > Projects',
      '/projects',
      'app/components/MobileNav.tsx',
      'Opens the project library for organizing armies, squads, commissions, and larger hobby goals.',
      'Fixed bottom navigation bar',
      'nav item named Projects',
      'The Projects icon and label in the bottom navigation',
      'top',
      20,
      array['global', 'navigation', 'projects']
    ),
    (
      'global.mobile_nav.paints',
      'Paints navigation',
      'navigation',
      'Global mobile nav > Paints',
      '/paints',
      'app/components/MobileNav.tsx',
      'Opens the paint vault for tracking owned paints, wishlisted paints, matching colors, custom mixes, and paint details.',
      'Fixed bottom navigation bar',
      'nav item named Paints',
      'The Paints icon and label in the bottom navigation',
      'top',
      30,
      array['global', 'navigation', 'paints', 'vault']
    ),
    (
      'global.mobile_nav.guides',
      'Guides navigation',
      'navigation',
      'Global mobile nav > Guides',
      '/guides',
      'app/components/MobileNav.tsx',
      'Opens the guide area for saved guides, reusable decks, and the public guide library.',
      'Fixed bottom navigation bar',
      'nav item named Guides',
      'The Guides icon and label in the bottom navigation',
      'top',
      40,
      array['global', 'navigation', 'guides', 'recipes']
    ),
    (
      'global.mobile_nav.themes',
      'Themes navigation',
      'navigation',
      'Global mobile nav > Themes',
      '/themes',
      'app/components/MobileNav.tsx',
      'Opens theme collections, where palettes, reference images, units, projects, and guides can be grouped by visual direction.',
      'Fixed bottom navigation bar',
      'nav item named Themes',
      'The Themes icon and label in the bottom navigation',
      'top',
      50,
      array['global', 'navigation', 'themes']
    ),
    (
      'global.settings',
      'Settings shortcut',
      'button',
      'Top bar > Settings',
      '/settings',
      'app/dashboard/dashboard-top-bar.tsx',
      'Opens profile, preferences, session controls, support, account, and legal settings.',
      'Top right of authenticated pages',
      'settings icon button',
      'The circular gear button in the top bar',
      'bottom-start',
      60,
      array['global', 'settings']
    ),
    (
      'global.curator',
      'The Curator',
      'button',
      'Global assistant button',
      '/dashboard',
      'app/components/curator/curator-button.tsx',
      'Opens The Curator, a contextual helper that gives hobby guidance, next-step suggestions, and app-specific assistance.',
      'Floating app assistant control',
      'button aria-label Open The Curator',
      'The floating Curator button and its chat panel',
      'top-end',
      70,
      array['global', 'assistant', 'curator']
    ),
    (
      'global.install_app',
      'Download app',
      'button',
      'Install prompt > Download app',
      '/dashboard',
      'app/components/download-app-button.tsx',
      'Installs Obsidian Gallery as an app when the browser supports the install prompt.',
      'Install or prompt area',
      'button aria-label Download app',
      'The download or install button',
      'top',
      80,
      array['global', 'pwa']
    ),
    (
      'dashboard.page',
      'Dashboard',
      'page',
      'Dashboard',
      '/dashboard',
      'app/dashboard/page.tsx',
      'The daily command center for active units, next actions, featured work, stats, XP, badges, and quick routes back into painting.',
      'Main dashboard page',
      'main dashboard content',
      'The whole dashboard viewport',
      'auto',
      100,
      array['dashboard', 'page']
    ),
    (
      'dashboard.help',
      'Dashboard explainer',
      'button',
      'Dashboard header > ?',
      '/dashboard',
      'app/dashboard/dashboard-v3-preview.tsx',
      'Explains what the dashboard is for: a quick check-in view for active units, next actions, and painting progress.',
      'Dashboard header',
      'button aria-label Show dashboard explanation',
      'The question mark button in the Dashboard header',
      'bottom-end',
      110,
      array['dashboard', 'help', 'popup']
    ),
    (
      'dashboard.add_next_action',
      'Add next action',
      'button',
      'Dashboard header > +',
      '/dashboard',
      'app/dashboard/dashboard-v3-preview.tsx',
      'Adds a new dashboard task to the next action list so the user has one more concrete step to follow.',
      'Dashboard header',
      'button aria-label Add next action',
      'The plus button beside the Dashboard help button',
      'bottom-end',
      120,
      array['dashboard', 'next-actions', 'button']
    ),
    (
      'dashboard.tabs.active_units',
      'Active Units tab',
      'tab',
      'Dashboard > Dashboard sections > Active Units',
      '/dashboard',
      'app/dashboard/dashboard-tabs.tsx',
      'Shows current bench work, the next action panel, featured unit progress, and units that are ready for attention.',
      'Below dashboard header',
      'tab named Active Units',
      'The Active Units segmented tab',
      'bottom',
      130,
      array['dashboard', 'tab', 'units']
    ),
    (
      'dashboard.tabs.my_progress',
      'My Progress tab',
      'tab',
      'Dashboard > Dashboard sections > My Progress',
      '/dashboard',
      'app/dashboard/dashboard-tabs.tsx',
      'Shows XP, streaks, badges, and stats so the user can understand their long-term hobby momentum.',
      'Below dashboard header',
      'tab named My Progress',
      'The My Progress segmented tab',
      'bottom',
      140,
      array['dashboard', 'tab', 'progress', 'xp']
    ),
    (
      'dashboard.next_actions.panel',
      'Next actions panel',
      'panel',
      'Dashboard > Next Actions',
      '/dashboard',
      'app/dashboard/dashboard-next-actions-card.tsx',
      'A short guided checklist chosen from the user onboarding goal. Each action has a completion control, a breadcrumb, and a route to the exact place to act.',
      'Near top of Active Units dashboard',
      'section aria-label User next actions',
      'The whole next actions card',
      'bottom',
      150,
      array['dashboard', 'next-actions', 'onboarding']
    ),
    (
      'dashboard.next_actions.complete_toggle',
      'Next action complete toggle',
      'toggle',
      'Dashboard > Next Actions > Completion button',
      '/dashboard',
      'app/dashboard/dashboard-next-actions-card.tsx',
      'Marks a suggested action complete or incomplete and updates checklist progress for the current onboarding flow.',
      'Left side of each next action row',
      'button aria-pressed in next action row',
      'The check box button at the start of an action row',
      'right',
      160,
      array['dashboard', 'next-actions', 'toggle']
    ),
    (
      'dashboard.next_actions.go',
      'Go to next action',
      'button',
      'Dashboard > Next Actions > Go',
      '/dashboard',
      'app/dashboard/dashboard-next-actions-card.tsx',
      'Navigates to the page and component referenced by the action so the user can perform the recommended step.',
      'Right side of each next action row',
      'link aria-label Go to action label',
      'The Go button at the end of an action row',
      'left',
      170,
      array['dashboard', 'next-actions', 'navigation']
    ),
    (
      'dashboard.next_actions.dismiss',
      'Dismiss next actions',
      'button',
      'Dashboard > Next Actions > Dismiss',
      '/dashboard',
      'app/dashboard/dashboard-next-actions-card.tsx',
      'Hides the onboarding next action checklist for the user when they do not want it on the dashboard.',
      'Top right of next actions card',
      'button aria-label Dismiss next actions',
      'The close button in the next actions card header',
      'left',
      180,
      array['dashboard', 'next-actions', 'dismiss']
    ),
    (
      'dashboard.quick_actions.start',
      'Start Project or Unit',
      'button',
      'Dashboard > Quick Actions > Start Project or Unit',
      '/dashboard',
      'app/dashboard/dashboard-quick-action-start-button.tsx',
      'Opens the flow for creating a new project or a new unit, depending on what the user wants to start tracking.',
      'Dashboard quick actions area',
      'button aria-label Start Project or Unit',
      'The Start Project or Unit quick action',
      'top',
      190,
      array['dashboard', 'quick-actions', 'projects', 'units']
    ),
    (
      'dashboard.quick_actions.paint_collection',
      'Build Your Collection',
      'button',
      'Dashboard > Quick Actions > Build Your Collection',
      '/dashboard',
      'app/dashboard/dashboard-quick-action-paint-button.tsx',
      'Sends the user to the paint vault to track owned paints, wishlist colors, and missing supplies.',
      'Dashboard quick actions area',
      'button aria-label Build Your Collection',
      'The paint collection quick action',
      'top',
      200,
      array['dashboard', 'quick-actions', 'paints']
    ),
    (
      'dashboard.featured_unit',
      'Featured unit',
      'card',
      'Dashboard > Featured Unit',
      '/dashboard',
      'app/dashboard/dashboard-unit-in-progress.tsx',
      'Highlights the unit the user is currently focusing on, including progress, stage, time logged, and a resume route.',
      'Active Units dashboard',
      'featured unit card',
      'The large featured unit card',
      'top',
      210,
      array['dashboard', 'units', 'progress']
    ),
    (
      'dashboard.resume_painting',
      'Resume painting',
      'button',
      'Dashboard > Featured Unit > Resume',
      '/dashboard',
      'app/dashboard/dashboard-resume-button.tsx',
      'Opens the active unit so the user can continue recording stages, photos, paints, and sessions.',
      'Featured unit card',
      'resume painting button',
      'The Resume button on a unit card',
      'left',
      220,
      array['dashboard', 'units', 'button']
    ),
    (
      'dashboard.xp_card',
      'XP progress',
      'status',
      'Dashboard > Progress > XP',
      '/dashboard',
      'app/dashboard/dashboard-xp-card.tsx',
      'Shows level, current XP, progress toward the next level, and gamified painting momentum.',
      'My Progress dashboard tab',
      'XP progress card',
      'The XP meter card',
      'bottom',
      230,
      array['dashboard', 'progress', 'xp']
    ),
    (
      'dashboard.hobby_badges',
      'Hobby badges',
      'status',
      'Dashboard > Progress > Badges',
      '/dashboard',
      'app/dashboard/dashboard-hobby-badges.tsx',
      'Shows earned and locked badges tied to milestones such as creating units, logging sessions, and finishing work.',
      'My Progress dashboard tab',
      'badges earned section',
      'The badge list or badge card area',
      'top',
      240,
      array['dashboard', 'progress', 'badges']
    ),
    (
      'projects.page',
      'Projects',
      'page',
      'Projects',
      '/projects',
      'app/projects/page.tsx',
      'The project library for organizing related units, images, palettes, themes, and progress under a larger hobby goal.',
      'Main projects page',
      'main projects content',
      'The whole projects viewport',
      'auto',
      300,
      array['projects', 'page']
    ),
    (
      'projects.help',
      'Projects explainer',
      'button',
      'Projects header > ?',
      '/projects',
      'app/projects/projects-v3-preview.tsx',
      'Explains that projects collect units, reference images, paints, and guides together around a larger goal.',
      'Projects header',
      'button aria-label About projects',
      'The question mark button in the Projects header',
      'bottom-end',
      310,
      array['projects', 'help', 'popup']
    ),
    (
      'projects.create_button',
      'Create project',
      'button',
      'Projects header > +',
      '/projects',
      'app/projects/projects-v3-preview.tsx',
      'Opens the new project form so the user can name a project, describe it, and start grouping units under it.',
      'Projects header',
      'button aria-label Create project',
      'The plus button in the Projects header',
      'bottom-end',
      320,
      array['projects', 'create', 'button']
    ),
    (
      'projects.create_form',
      'Project create form',
      'form',
      'Projects > Create Project',
      '/projects?tab=create',
      'app/projects/project-create-form.tsx',
      'Creates a project with a name, description, optional status context, and room to gather units and images.',
      'Project creation panel',
      'project create form',
      'The create project form fields and submit button',
      'top',
      330,
      array['projects', 'create', 'form']
    ),
    (
      'projects.card',
      'Project card',
      'card',
      'Projects > Project list',
      '/projects',
      'components/projects/project-tile.tsx',
      'Summarizes one project with its image, status, unit count, progress, and route to the project detail page.',
      'Projects grid or list',
      'project card',
      'A single project tile or list row',
      'top',
      340,
      array['projects', 'card']
    ),
    (
      'projects.detail.page',
      'Project detail',
      'page',
      'Projects > Project Detail',
      '/projects/[id]',
      'app/projects/[id]/page.tsx',
      'Shows one project in detail, including overview, units, gallery images, palettes, theme links, and deletion controls.',
      'Project detail page',
      'project detail content',
      'The project detail viewport',
      'auto',
      350,
      array['projects', 'detail']
    ),
    (
      'projects.detail.tabs',
      'Project detail tabs',
      'tab',
      'Project Detail > Tabs',
      '/projects/[id]',
      'app/projects/[id]/project-detail-tabs.tsx',
      'Switches between project details, attached units, gallery images, and palette/theme work.',
      'Below project hero',
      'project detail tabs',
      'The segmented project detail tab row',
      'bottom',
      360,
      array['projects', 'detail', 'tabs']
    ),
    (
      'projects.add_unit_tab',
      'Add unit to project',
      'form',
      'Project Detail > Add Unit',
      '/projects/[id]',
      'app/projects/[id]/project-add-unit-tab.tsx',
      'Attaches existing units to a project or helps route the user toward creating another unit for the project.',
      'Project units tab',
      'project add unit tab',
      'The add unit controls in the project units tab',
      'top',
      370,
      array['projects', 'units', 'form']
    ),
    (
      'projects.gallery',
      'Project gallery',
      'panel',
      'Project Detail > Gallery',
      '/projects/[id]',
      'app/projects/[id]/project-gallery-card.tsx',
      'Stores reference, progress, and showcase images for a project, with controls for upload, captions, and removal.',
      'Project gallery tab or card',
      'project gallery card',
      'The project image gallery panel',
      'top',
      380,
      array['projects', 'gallery', 'images']
    ),
    (
      'projects.palette_starter',
      'Project palette starter',
      'panel',
      'Project Detail > Palette',
      '/projects/[id]',
      'app/projects/[id]/project-palette-starter.tsx',
      'Starts a color palette for the project and can connect visual direction to themes and paints.',
      'Project palette area',
      'project palette starter',
      'The project palette starter panel',
      'top',
      390,
      array['projects', 'palette', 'themes']
    ),
    (
      'paints.page',
      'Paint Vault',
      'page',
      'Paints',
      '/paints',
      'app/paints/page.tsx',
      'The paint collection area for searching paints, marking ownership, building wishlists, matching colors, creating custom mixes, and exporting records.',
      'Main paints page',
      'main paints content',
      'The whole paint vault viewport',
      'auto',
      400,
      array['paints', 'vault', 'page']
    ),
    (
      'paints.help',
      'Paint Vault explainer',
      'button',
      'Paint Vault header > ?',
      '/paints',
      'app/paints/paints-v3-preview.tsx',
      'Explains the paint vault: tracking owned and wanted paints, avoiding duplicates, exporting, and connecting paints to guides and themes.',
      'Paint Vault header',
      'button aria-label About paint vault',
      'The question mark button in the Paint Vault header',
      'bottom-end',
      410,
      array['paints', 'help', 'popup']
    ),
    (
      'paints.create_custom_mix',
      'Create custom mix',
      'button',
      'Paint Vault header > +',
      '/paints',
      'app/paints/paints-v3-preview.tsx',
      'Opens the custom mix dialog so the user can save a mixed color recipe based on paints in their collection.',
      'Paint Vault header',
      'button aria-label Create custom mix',
      'The plus button in the Paint Vault header',
      'bottom-end',
      420,
      array['paints', 'custom-mix', 'button']
    ),
    (
      'paints.tabs.my_paints',
      'My Paints tab',
      'tab',
      'Paint Vault > Paint views > My Paints',
      '/paints',
      'app/paints/paints-v3-preview.tsx',
      'Filters the paint vault to paints the user owns or has marked for their collection.',
      'Below Paint Vault header',
      'tab named My Paints',
      'The My Paints segmented tab',
      'bottom',
      430,
      array['paints', 'tab', 'owned']
    ),
    (
      'paints.tabs.library',
      'Paint Library tab',
      'tab',
      'Paint Vault > Paint views > Paint Library',
      '/paints',
      'app/paints/paints-v3-preview.tsx',
      'Shows the broader paint catalog so the user can discover paints and add them to owned or wishlist states.',
      'Below Paint Vault header',
      'tab named Paint Library',
      'The Paint Library segmented tab',
      'bottom',
      440,
      array['paints', 'tab', 'library']
    ),
    (
      'paints.search',
      'Paint search',
      'search',
      'Paint Vault > Search',
      '/paints',
      'app/paints/paints-v3-preview.tsx',
      'Searches paints by name, brand, or line and narrows the swatch grid immediately.',
      'Paint search and filter area',
      'input placeholder Search by name or brand',
      'The paint search input',
      'bottom',
      450,
      array['paints', 'search']
    ),
    (
      'paints.filters',
      'Paint filters',
      'filter',
      'Paint Vault > Filters',
      '/paints',
      'app/paints/paints-v3-preview.tsx',
      'Filters paints by brand, line, ownership state, color group, and nearest match color.',
      'Paint search and filter area',
      'filter controls',
      'The paint filter panel and filter button',
      'bottom',
      460,
      array['paints', 'filter']
    ),
    (
      'paints.match_color',
      'Match a color',
      'filter',
      'Paint Vault > Filters > Match a Color',
      '/paints',
      'app/paints/paints-v3-preview.tsx',
      'Lets the user choose a color and finds nearby paints in the catalog.',
      'Paint filter panel',
      'input aria-label Match a color',
      'The Match a Color filter control',
      'top',
      470,
      array['paints', 'filter', 'color-match']
    ),
    (
      'paints.export',
      'Export paints',
      'export',
      'Paint Vault > Export',
      '/paints',
      'app/paints/paints-v3-preview.tsx',
      'Exports the current visible paint records as CSV, TXT, JSON, or printable PDF-style output.',
      'Paint list toolbar',
      'button text Export',
      'The Export button and export dialog',
      'top',
      480,
      array['paints', 'export']
    ),
    (
      'paints.swatch_grid',
      'Paint swatch grid',
      'panel',
      'Paint Vault > Paint swatches',
      '/paints',
      'app/paints/paints-v3-preview.tsx',
      'Displays paint colors as selectable swatches with ownership and wishlist indicators.',
      'Paint list body',
      'section aria-label Paint swatches',
      'The paint swatch grid',
      'top',
      490,
      array['paints', 'swatches']
    ),
    (
      'paints.paint_info_panel',
      'Paint info panel',
      'panel',
      'Paint Vault > Selected paint',
      '/paints',
      'app/paints/paints-v3-preview.tsx',
      'Shows details for the selected paint, including brand, line, finish, size, notes, ownership, wishlist state, and a detail route.',
      'Bottom paint detail sheet',
      'paint info panel',
      'The fixed selected paint panel at the bottom',
      'top',
      500,
      array['paints', 'paint-detail']
    ),
    (
      'vault.page',
      'Vault',
      'page',
      'Vault',
      '/vault',
      'app/vault/page.tsx',
      'The live paint vault route with collection, catalog search, custom paint forms, ownership controls, barcode scanning, color matching, and batch tools.',
      'Main vault page',
      'vault page content',
      'The whole vault viewport',
      'auto',
      510,
      array['vault', 'paints', 'page']
    ),
    (
      'vault.tabs.collection',
      'My Paints vault tab',
      'tab',
      'Vault > My Paints',
      '/vault?tab=collection',
      'app/vault/vault-segmented-tabs.tsx',
      'Shows the user-owned collection view and defaults ownership filtering toward owned paints.',
      'Top of vault page',
      'tab named My Paints',
      'The My Paints segment in the vault tab row',
      'bottom',
      520,
      array['vault', 'tab', 'owned']
    ),
    (
      'vault.tabs.find',
      'Find Paint vault tab',
      'tab',
      'Vault > Find Paint',
      '/vault?tab=find',
      'app/vault/vault-segmented-tabs.tsx',
      'Shows catalog search and filters for finding paints across the full catalog.',
      'Top of vault page',
      'tab named Find Paint',
      'The Find Paint segment in the vault tab row',
      'bottom',
      530,
      array['vault', 'tab', 'search']
    ),
    (
      'vault.tabs.custom',
      'Custom Mix vault tab',
      'tab',
      'Vault > Custom Mix',
      '/vault?tab=custom',
      'app/vault/vault-segmented-tabs.tsx',
      'Opens the custom paint area where the user can record self-made mixes and formula details.',
      'Top of vault page',
      'tab named Custom Mix',
      'The Custom Mix segment in the vault tab row',
      'bottom',
      540,
      array['vault', 'tab', 'custom-paint']
    ),
    (
      'vault.filters',
      'Vault filters',
      'filter',
      'Vault > Filters',
      '/vault',
      'app/vault/vault-filters-client.tsx',
      'Filters catalog and collection rows by query, brand, line, ownership, and color match details.',
      'Vault filter panel',
      'vault filters form',
      'The live vault filter controls',
      'bottom',
      550,
      array['vault', 'filter']
    ),
    (
      'vault.barcode_scanner',
      'Scan barcode',
      'button',
      'Vault > Filters > Scan barcode',
      '/vault',
      'app/vault/barcode-scanner-modal.tsx',
      'Opens the barcode scanner to look up paints or paint sets from a product barcode.',
      'Vault filter panel',
      'button aria-label Scan barcode',
      'The barcode scan button beside vault filters',
      'bottom',
      560,
      array['vault', 'barcode', 'paints']
    ),
    (
      'vault.color_match_modal',
      'Color matcher',
      'modal',
      'Vault > Color Match',
      '/vault',
      'app/vault/color-match-modal.tsx',
      'Lets the user choose a color and compare the nearest paint catalog matches.',
      'Vault modal layer',
      'color matcher dialog',
      'The color matcher dialog and color wheel',
      'auto',
      570,
      array['vault', 'color-match', 'modal']
    ),
    (
      'vault.batch_actions',
      'Batch paint actions',
      'panel',
      'Vault > Batch actions',
      '/vault',
      'app/vault/vault-batch-actions.tsx',
      'Applies ownership or wishlist actions to multiple selected paints and supports paint set workflows.',
      'Vault batch action area',
      'vault batch actions panel',
      'The batch action toolbar or panel',
      'top',
      580,
      array['vault', 'batch', 'paints']
    ),
    (
      'vault.export_button',
      'Vault export',
      'export',
      'Vault > Export',
      '/vault',
      'app/vault/vault-export-button.tsx',
      'Exports paint data from the live vault for spreadsheets, backups, or external use.',
      'Vault toolbar',
      'vault export button',
      'The vault export button and export dialog',
      'top',
      590,
      array['vault', 'export']
    ),
    (
      'vault.paint_detail',
      'Paint detail page',
      'page',
      'Vault > Paint Detail',
      '/vault/[source]/[id]',
      'app/vault/[source]/[id]/page.tsx',
      'Shows one paint with technical specs, ownership state, conversion recommendations, and guides that use the paint.',
      'Paint detail page',
      'paint detail content',
      'The whole paint detail viewport',
      'auto',
      600,
      array['vault', 'paint-detail']
    ),
    (
      'vault.paint_ownership',
      'Paint ownership controls',
      'toggle',
      'Paint Detail > Ownership',
      '/vault/[source]/[id]',
      'app/vault/[source]/[id]/paint-ownership-controls.tsx',
      'Marks a paint as owned, not owned, wishlisted, or otherwise managed in the user collection.',
      'Paint ownership card',
      'paint ownership controls',
      'The ownership buttons on a paint detail page',
      'top',
      610,
      array['vault', 'ownership', 'paints']
    ),
    (
      'vault.paint_conversions',
      'Paint conversion chart',
      'panel',
      'Paint Detail > Conversion Chart',
      '/vault/[source]/[id]',
      'app/vault/[source]/[id]/paint-conversion-chart-grid.tsx',
      'Lists recommended equivalent paints and similarity matches across brands and lines.',
      'Paint detail conversion area',
      'paint conversion chart',
      'The conversion recommendation grid',
      'top',
      620,
      array['vault', 'conversions', 'paints']
    ),
    (
      'guides.page',
      'Guides',
      'page',
      'Guides',
      '/guides',
      'app/guides/page.tsx',
      'The guide hub for saved guides, reusable decks, and the public library of guides and decks.',
      'Main guides page',
      'main guides content',
      'The whole guides viewport',
      'auto',
      700,
      array['guides', 'page']
    ),
    (
      'guides.help',
      'Guides explainer',
      'button',
      'Guides header > ?',
      '/guides',
      'app/guides/guides-v3-preview.tsx',
      'Explains that guides are collections of decks, decks are step-card sequences, and the library is where public items can be found and saved.',
      'Guides header',
      'button aria-label About guides',
      'The question mark button in the Guides header',
      'bottom-end',
      710,
      array['guides', 'help', 'popup']
    ),
    (
      'guides.create_button',
      'Create guide or deck',
      'button',
      'Guides header > +',
      '/guides',
      'app/guides/guides-v3-preview.tsx',
      'Opens the forge flow for creating either a full guide or a reusable step-card deck.',
      'Guides header',
      'button aria-label Create guide or deck',
      'The plus button in the Guides header',
      'bottom-end',
      720,
      array['guides', 'create', 'button']
    ),
    (
      'guides.tabs.guides',
      'Guides tab',
      'tab',
      'Guides > Guide sections > Guides',
      '/guides',
      'app/guides/guides-v3-preview.tsx',
      'Shows complete guide files assembled from one or more decks.',
      'Below Guides header',
      'tab named Guides',
      'The Guides segmented tab',
      'bottom',
      730,
      array['guides', 'tab']
    ),
    (
      'guides.tabs.decks',
      'Decks tab',
      'tab',
      'Guides > Guide sections > Decks',
      '/guides',
      'app/guides/guides-v3-preview.tsx',
      'Shows reusable card sequences for a material, technique, recipe step, or result.',
      'Below Guides header',
      'tab named Decks',
      'The Decks segmented tab',
      'bottom',
      740,
      array['guides', 'decks', 'tab']
    ),
    (
      'guides.tabs.library',
      'Library tab',
      'tab',
      'Guides > Guide sections > Library',
      '/guides',
      'app/guides/guides-v3-preview.tsx',
      'Shows public guides and decks that can be searched, inspected, and saved.',
      'Below Guides header',
      'tab named Library',
      'The Library segmented tab',
      'bottom',
      750,
      array['guides', 'library', 'tab']
    ),
    (
      'guides.library_search',
      'Guide library search',
      'search',
      'Guides > Library > Search',
      '/guides',
      'app/guides/guides-v3-preview.tsx',
      'Searches public guide and deck entries by title, subtitle, and level.',
      'Library tab',
      'input placeholder Search guides and decks',
      'The library search input',
      'bottom',
      760,
      array['guides', 'library', 'search']
    ),
    (
      'guides.deck_save',
      'Save deck',
      'toggle',
      'Guides > Library > Save Deck',
      '/guides',
      'app/guides/guides-v3-preview.tsx',
      'Saves or removes a public deck from the user library.',
      'Deck card action area',
      'button aria-label Save or Remove deck title',
      'The save toggle on a deck card',
      'left',
      770,
      array['guides', 'decks', 'save']
    ),
    (
      'guides.forge.mode',
      'Guide forge mode',
      'toggle',
      'Guides > Create > Guide or Deck',
      '/guides',
      'app/guides/guides-v3-preview.tsx',
      'Chooses whether the forge creates a full guide assembled from decks or a standalone deck of cards.',
      'Create guide/deck modal',
      'forge mode selector',
      'The Guide and Deck choice controls',
      'bottom',
      780,
      array['guides', 'create', 'forge']
    ),
    (
      'guides.forge.deck_picker',
      'Select guide decks',
      'workflow',
      'Guides > Create Guide > Select Decks',
      '/guides',
      'app/guides/guides-v3-preview.tsx',
      'Lets the user choose saved decks that will become the ordered contents of a new guide.',
      'Create Guide flow',
      'guide deck picker',
      'The deck selection list in the forge',
      'top',
      790,
      array['guides', 'create', 'decks']
    ),
    (
      'guides.forge.compose',
      'Guide details',
      'form',
      'Guides > Create Guide > Guide Details',
      '/guides',
      'app/guides/guides-v3-preview.tsx',
      'Collects guide name, description, cover image, and final save details.',
      'Create Guide flow',
      'guide details form',
      'The guide details form in the forge',
      'top',
      800,
      array['guides', 'create', 'form']
    ),
    (
      'recipes.page',
      'Guide library',
      'page',
      'Recipes',
      '/recipes',
      'app/recipes/page.tsx',
      'The live guide library for browsing public guides and managing the user''s own step-by-step painting guides.',
      'Main recipes/guides page',
      'guide-library',
      'The whole recipes guide library viewport',
      'auto',
      810,
      array['recipes', 'guides', 'page']
    ),
    (
      'recipes.create_form',
      'Create guide form',
      'form',
      'Guides > Create',
      '/recipes?tab=custom',
      'app/recipes/create-recipe-form.tsx',
      'Creates a new painting guide with name, description, visibility, and image context.',
      'Create guide tab',
      'form id create-guide-form',
      'The create guide form',
      'top',
      820,
      array['recipes', 'guides', 'create']
    ),
    (
      'recipes.detail.page',
      'Guide detail',
      'page',
      'Guides > Guide Detail',
      '/recipes/[id]',
      'app/recipes/[id]/page.tsx',
      'Shows a saved guide with hero details, steps, paints, gallery images, inventory coverage, video, visibility, sharing, and export options.',
      'Guide detail page',
      'recipe detail content',
      'The whole guide detail viewport',
      'auto',
      830,
      array['recipes', 'guides', 'detail']
    ),
    (
      'recipes.detail.tabs',
      'Guide detail tabs',
      'tab',
      'Guide Detail > Tabs',
      '/recipes/[id]',
      'app/recipes/[id]/recipe-detail-tabs.tsx',
      'Switches between guide details, steps, adding a step, gallery images, inventory, and video/card export areas.',
      'Below guide hero',
      'recipe detail tabs',
      'The guide detail tab row',
      'bottom',
      840,
      array['recipes', 'guides', 'tabs']
    ),
    (
      'recipes.add_step',
      'Add guide step',
      'form',
      'Guide Detail > Add Step',
      '/recipes/[id]',
      'app/recipes/[id]/recipe-add-step-tab.tsx',
      'Adds an ordered painting step with instructions, paints, quantities, and optional stage context.',
      'Guide add step tab',
      'recipe add step form',
      'The add guide step form',
      'top',
      850,
      array['recipes', 'guides', 'steps']
    ),
    (
      'recipes.step_card',
      'Guide step card',
      'card',
      'Guide Detail > Steps > Step Card',
      '/recipes/[id]',
      'app/recipes/[id]/components/recipe-step-card.tsx',
      'Displays one guide step with instructions, linked paints, photo controls, and edit or remove actions.',
      'Guide steps tab',
      'recipe step card',
      'A single guide step card',
      'top',
      860,
      array['recipes', 'guides', 'steps']
    ),
    (
      'recipes.paint_picker',
      'Guide paint picker',
      'modal',
      'Guide Detail > Add Paint',
      '/recipes/[id]',
      'app/recipes/[id]/components/paint-picker.tsx',
      'Searches and selects paints to attach to a guide step, including custom paints where available.',
      'Guide step paint controls',
      'recipe paint picker',
      'The paint picker button and dialog',
      'top',
      870,
      array['recipes', 'guides', 'paints']
    ),
    (
      'recipes.visibility',
      'Guide visibility',
      'toggle',
      'Guide Detail > Visibility',
      '/recipes/[id]',
      'app/recipes/[id]/components/recipe-visibility-pill.tsx',
      'Switches a guide between private and public visibility with confirmation.',
      'Guide hero area',
      'recipe visibility pill',
      'The public/private visibility pill',
      'bottom',
      880,
      array['recipes', 'guides', 'visibility']
    ),
    (
      'recipes.gallery',
      'Guide gallery',
      'panel',
      'Guide Detail > Gallery',
      '/recipes/[id]',
      'app/recipes/[id]/components/recipe-gallery-section.tsx',
      'Uploads, captions, expands, reorders, and removes images attached to a guide.',
      'Guide gallery tab',
      'recipe gallery section',
      'The guide gallery image panel',
      'top',
      890,
      array['recipes', 'guides', 'gallery']
    ),
    (
      'recipes.guide_cards',
      'Guide cards export',
      'modal',
      'Guide Detail > Guide Cards',
      '/recipes/[id]',
      'app/recipes/[id]/recipe-guide-dialog.tsx',
      'Renders guide steps as shareable card images and supports exporting, zipping, PDF generation, and share copy.',
      'Guide card modal',
      'recipe guide dialog',
      'The guide card preview and action panel',
      'auto',
      900,
      array['recipes', 'guides', 'export', 'share']
    ),
    (
      'themes.page',
      'Themes',
      'page',
      'Themes',
      '/themes',
      'app/themes/page.tsx',
      'The theme hub for color palettes, reference images, and visual systems connected to projects, units, guides, and paints.',
      'Main themes page',
      'main themes content',
      'The whole themes viewport',
      'auto',
      1000,
      array['themes', 'page']
    ),
    (
      'themes.help',
      'Themes explainer',
      'button',
      'Themes header > ?',
      '/themes',
      'app/themes/themes-v3-preview.tsx',
      'Explains that themes collect palettes, references, paints, units, projects, and guides under one visual direction.',
      'Themes header',
      'button aria-label About themes',
      'The question mark button in the Themes header',
      'bottom-end',
      1010,
      array['themes', 'help', 'popup']
    ),
    (
      'themes.create_button',
      'Create theme',
      'button',
      'Themes header > +',
      '/themes',
      'app/themes/themes-v3-preview.tsx',
      'Opens the theme creation panel so the user can start a new visual direction with palette and reference details.',
      'Themes header',
      'button aria-label Create theme',
      'The plus button in the Themes header',
      'bottom-end',
      1020,
      array['themes', 'create', 'button']
    ),
    (
      'themes.tabs.mine',
      'My Themes tab',
      'tab',
      'Themes > Theme views > My Themes',
      '/themes',
      'app/themes/themes-v3-preview.tsx',
      'Shows the user''s saved private and public theme collections.',
      'Below Themes header',
      'tab named My Themes',
      'The My Themes segmented tab',
      'bottom',
      1030,
      array['themes', 'tab']
    ),
    (
      'themes.tabs.library',
      'Theme Library tab',
      'tab',
      'Themes > Theme views > Theme Library',
      '/themes',
      'app/themes/themes-v3-preview.tsx',
      'Shows shared or public themes that can inspire palettes and project color directions.',
      'Below Themes header',
      'tab named Theme Library',
      'The Theme Library segmented tab',
      'bottom',
      1040,
      array['themes', 'library', 'tab']
    ),
    (
      'themes.form',
      'Theme form',
      'form',
      'Themes > Create Theme',
      '/themes',
      'app/themes/theme-form.tsx',
      'Creates or edits a theme with name, description, palette, visibility, and optional image context.',
      'Theme create or edit panel',
      'theme form',
      'The theme form fields and save button',
      'top',
      1050,
      array['themes', 'create', 'form']
    ),
    (
      'themes.detail.page',
      'Theme detail',
      'page',
      'Themes > Theme Detail',
      '/themes/[id]',
      'app/themes/[id]/page.tsx',
      'Shows one theme with hero image, palette editor, assignment controls, reference gallery, and public/private status.',
      'Theme detail page',
      'theme detail content',
      'The whole theme detail viewport',
      'auto',
      1060,
      array['themes', 'detail']
    ),
    (
      'themes.palette_editor',
      'Theme palette editor',
      'panel',
      'Theme Detail > Palette',
      '/themes/[id]',
      'app/themes/[id]/theme-palette-editor.tsx',
      'Adds, edits, removes, and organizes colors in a theme palette.',
      'Theme detail palette area',
      'theme palette editor',
      'The theme palette editor panel',
      'top',
      1070,
      array['themes', 'palette']
    ),
    (
      'themes.assignment_panel',
      'Theme assignment panel',
      'panel',
      'Theme Detail > Assignments',
      '/themes/[id]',
      'app/themes/[id]/theme-assignment-panel.tsx',
      'Connects the theme to projects, units, and guides so related hobby work shares a visual direction.',
      'Theme assignment area',
      'theme assignment panel',
      'The assignment controls on a theme detail page',
      'top',
      1080,
      array['themes', 'assignments']
    ),
    (
      'themes.image_gallery',
      'Theme image gallery',
      'panel',
      'Theme Detail > Gallery',
      '/themes/[id]',
      'app/themes/[id]/theme-image-gallery.tsx',
      'Uploads, captions, expands, matches colors from, and removes reference images for a theme.',
      'Theme detail gallery area',
      'theme image gallery',
      'The theme image gallery panel',
      'top',
      1090,
      array['themes', 'gallery', 'images']
    ),
    (
      'themes.image_color_match',
      'Match paint from theme image',
      'button',
      'Theme Detail > Image > Match Paint',
      '/themes/[id]',
      'app/themes/[id]/theme-detail-hero.tsx',
      'Samples or routes a theme image color into paint matching so the user can find nearby paints.',
      'Theme image controls',
      'button aria-label Match Paint from theme image',
      'The Match Paint button on a theme image',
      'top',
      1100,
      array['themes', 'images', 'paints', 'color-match']
    ),
    (
      'units.new.page',
      'New unit',
      'page',
      'Units > New Unit',
      '/units/new',
      'app/units/new/page.tsx',
      'Creates a trackable model, squad, unit, or hobby item with status, project, images, and optional theme context.',
      'New unit page',
      'new unit page content',
      'The whole new unit form viewport',
      'auto',
      1200,
      array['units', 'create', 'page']
    ),
    (
      'units.new.form',
      'New unit form',
      'form',
      'Units > New Unit > Form',
      '/units/new',
      'app/units/new/new-unit-form.tsx',
      'Captures the unit name, description, project links, status, image, and starter metadata needed to add a model to the bench.',
      'New unit page form',
      'new-unit-form',
      'The new unit form fields and submit button',
      'top',
      1210,
      array['units', 'create', 'form']
    ),
    (
      'units.detail.page',
      'Unit detail',
      'page',
      'Units > Unit Detail',
      '/units/[id]',
      'app/units/[id]/page.tsx',
      'Shows one unit with hero details, stages, paints, gallery, session tracking, scheduling, sharing, and project/theme context.',
      'Unit detail page',
      'unit detail content',
      'The whole unit detail viewport',
      'auto',
      1220,
      array['units', 'detail']
    ),
    (
      'units.detail.tabs',
      'Unit sections',
      'tab',
      'Unit Detail > Sections',
      '/units/[id]',
      'app/units/[id]/unit-detail-client.tsx',
      'Switches between the unit overview, paint progress, gallery, sessions, and scheduling views.',
      'Below unit hero',
      'unit section tabs',
      'The unit section segmented tab row',
      'bottom',
      1230,
      array['units', 'tabs']
    ),
    (
      'units.progress.stage_selector',
      'Stage selector',
      'tab',
      'Unit Detail > Progress > Stage selector',
      '/units/[id]',
      'app/units/[id]/unit-progress-tab.tsx',
      'Selects a painting stage so the user can track its guide, paints, photos, notes, and completion status.',
      'Unit progress tab',
      'stage selector',
      'The stage selection buttons',
      'bottom',
      1240,
      array['units', 'progress', 'stages']
    ),
    (
      'units.progress.stage_complete',
      'Stage complete toggle',
      'toggle',
      'Unit Detail > Progress > Toggle completion',
      '/units/[id]',
      'app/units/[id]/unit-progress-tab.tsx',
      'Marks the selected stage complete or incomplete and contributes to the unit progress meter.',
      'Unit progress selected stage',
      'button aria-label Toggle stage completion',
      'The selected stage completion button',
      'left',
      1250,
      array['units', 'progress', 'toggle']
    ),
    (
      'units.progress.stage_paints',
      'Stage paints',
      'panel',
      'Unit Detail > Progress > Paints',
      '/units/[id]',
      'app/units/[id]/unit-progress-tab.tsx',
      'Shows paints linked to a unit stage and supports opening paint details or removing paints from that stage.',
      'Unit progress selected stage',
      'stage paint list',
      'The stage paints list',
      'top',
      1260,
      array['units', 'progress', 'paints']
    ),
    (
      'units.progress.stage_photo',
      'Stage photo',
      'button',
      'Unit Detail > Progress > Photo',
      '/units/[id]',
      'app/units/[id]/unit-progress-tab.tsx',
      'Expands a stage photo so the user can inspect progress images at a larger size.',
      'Unit progress selected stage',
      'button aria-label Expand stage photo',
      'A stage photo expand button',
      'top',
      1270,
      array['units', 'progress', 'images']
    ),
    (
      'units.gallery',
      'Unit gallery',
      'panel',
      'Unit Detail > Gallery',
      '/units/[id]',
      'app/units/[id]/components/unit-gallery-section.tsx',
      'Uploads, captions, expands, selects, and removes unit images for progress and showcase tracking.',
      'Unit gallery tab',
      'unit gallery section',
      'The unit gallery image panel',
      'top',
      1280,
      array['units', 'gallery', 'images']
    ),
    (
      'units.session_tracker',
      'Session tracker',
      'panel',
      'Unit Detail > Sessions > Timer',
      '/units/[id]',
      'app/units/[id]/components/unit-session-tracker.tsx',
      'Starts, pauses, resumes, finishes, edits, deletes, and manually logs painting sessions for a unit.',
      'Unit sessions tab',
      'unit session tracker',
      'The session timer and manual log controls',
      'top',
      1290,
      array['units', 'sessions', 'timer']
    ),
    (
      'units.session_manual_log',
      'Log session manually',
      'button',
      'Unit Detail > Sessions > Log manually',
      '/units/[id]',
      'app/units/[id]/components/unit-session-tracker.tsx',
      'Opens manual session logging for backfilling painting time with notes and start/end details.',
      'Unit sessions tab',
      'button aria-label Log session manually',
      'The Log session manually button',
      'top',
      1300,
      array['units', 'sessions', 'manual-log']
    ),
    (
      'units.session_scheduler',
      'Session scheduler',
      'panel',
      'Unit Detail > Schedule',
      '/units/[id]',
      'app/units/[id]/components/unit-session-scheduler.tsx',
      'Schedules planned painting sessions on a calendar and tracks whether scheduled work was completed.',
      'Unit schedule tab',
      'unit session scheduler',
      'The session scheduler calendar and form',
      'top',
      1310,
      array['units', 'sessions', 'schedule']
    ),
    (
      'units.share_completed',
      'Share completed unit',
      'modal',
      'Unit Detail > Share',
      '/units/[id]',
      'components/share/UnitCompletedShareModal.tsx',
      'Builds a shareable completed-unit card, chooses an image, previews it, and exports or shares the result.',
      'Unit completion/share flow',
      'unit completed share modal',
      'The completed unit share dialog',
      'auto',
      1320,
      array['units', 'share', 'export']
    ),
    (
      'contests.page',
      'Contests',
      'page',
      'Contests',
      '/contests',
      'app/contests/page.tsx',
      'Lists public and available contests where users can nominate work, vote, and view results based on contest phase.',
      'Main contests page',
      'contest list content',
      'The whole contests viewport',
      'auto',
      1400,
      array['contests', 'page']
    ),
    (
      'contests.card',
      'Contest card',
      'card',
      'Contests > Contest card',
      '/contests',
      'components/contests/contest-card.tsx',
      'Summarizes contest title, phase, schedule, allowed nominee types, and route to submit, vote, or view details.',
      'Contest list',
      'contest card',
      'A single contest card',
      'top',
      1410,
      array['contests', 'card']
    ),
    (
      'contests.detail',
      'Contest detail',
      'page',
      'Contests > Contest Detail',
      '/contests/[slug]',
      'app/contests/[slug]/page.tsx',
      'Shows contest overview, allowed submission types, schedule, current phase, nominees, and contest actions.',
      'Contest detail page',
      'contest detail content',
      'The whole contest detail viewport',
      'auto',
      1420,
      array['contests', 'detail']
    ),
    (
      'contests.submit',
      'Submit nomination',
      'form',
      'Contest Detail > Submit',
      '/contests/[slug]/submit',
      'app/contests/[slug]/submit/page.tsx',
      'Lets the user nominate an eligible project, unit, or guide into a contest.',
      'Contest submission page',
      'nomination source picker',
      'The contest nomination form and source picker',
      'top',
      1430,
      array['contests', 'submit', 'nomination']
    ),
    (
      'contests.vote',
      'Vote in contest',
      'form',
      'Contest Detail > Vote',
      '/contests/[slug]/vote',
      'app/contests/[slug]/vote/page.tsx',
      'Presents approved nominees and records the user ballot using approval or ranked voting rules.',
      'Contest voting page',
      'contest ballot',
      'The contest ballot controls',
      'top',
      1440,
      array['contests', 'vote', 'ballot']
    ),
    (
      'contests.results',
      'Contest results',
      'page',
      'Contest Detail > Results',
      '/contests/[slug]/results',
      'app/contests/[slug]/results/page.tsx',
      'Shows published contest results, podium, rankings, vote totals, and tied placements.',
      'Contest results page',
      'contest results table',
      'The contest results podium and table',
      'auto',
      1450,
      array['contests', 'results']
    ),
    (
      'contests.manage',
      'Manage contests',
      'page',
      'Contests > Manage',
      '/contests/manage',
      'app/contests/manage/page.tsx',
      'Administrative area for creating, editing, previewing, moderating, and publishing contest configuration.',
      'Contest management page',
      'contest management content',
      'The whole contest management viewport',
      'auto',
      1460,
      array['contests', 'admin']
    ),
    (
      'contests.manage.form',
      'Contest admin form',
      'form',
      'Contests > Manage > Form',
      '/contests/manage/[id]',
      'components/contests/contest-admin-form.tsx',
      'Configures contest title, schedule, visibility, allowed nominee types, voting method, voter access, and moderation settings.',
      'Contest admin edit page',
      'contest admin form',
      'The contest admin form controls',
      'top',
      1470,
      array['contests', 'admin', 'form']
    ),
    (
      'contests.dice_roll',
      'Campaign dice roll',
      'form',
      'Contests > Dice Roll',
      '/contests/dice-roll',
      'app/contests/dice-roll/dice-roll-form.tsx',
      'Records campaign dice rolls with reason, visibility, and audit context.',
      'Campaign dice roll page',
      'dice roll form',
      'The campaign dice roll form',
      'top',
      1480,
      array['contests', 'campaign', 'dice']
    ),
    (
      'onboarding.page',
      'Onboarding',
      'workflow',
      'Onboarding',
      '/onboarding',
      'app/onboarding/page.tsx',
      'Guides new users through legal acceptance, goals, pain points, workflow preference, first project or guide creation, and the Curator handoff.',
      'Onboarding flow',
      'onboarding shell',
      'The full onboarding screen',
      'auto',
      1500,
      array['onboarding', 'workflow']
    ),
    (
      'onboarding.legal',
      'Legal acceptance',
      'form',
      'Onboarding > Legal',
      '/onboarding',
      'app/onboarding/components/screens/legal-screen.tsx',
      'Collects terms and privacy acknowledgement before continuing into account setup.',
      'First onboarding step',
      'legal screen',
      'The legal acknowledgement controls',
      'top',
      1510,
      array['onboarding', 'legal']
    ),
    (
      'onboarding.goal',
      'Goal selection',
      'form',
      'Onboarding > Goal',
      '/onboarding',
      'app/onboarding/components/screens/goal-screen.tsx',
      'Asks what would help most right now and chooses the onboarding action flow that appears on the dashboard.',
      'Goal onboarding step',
      'goal screen',
      'The goal option cards',
      'top',
      1520,
      array['onboarding', 'goal', 'next-actions']
    ),
    (
      'onboarding.problem',
      'Problem selection',
      'form',
      'Onboarding > Problems',
      '/onboarding',
      'app/onboarding/components/screens/problem-screen.tsx',
      'Lets the user identify pain points so onboarding language and recommendations can match their needs.',
      'Problem onboarding step',
      'problem screen',
      'The problem option buttons',
      'top',
      1530,
      array['onboarding', 'personalization']
    ),
    (
      'onboarding.workflow',
      'Workflow preview',
      'workflow',
      'Onboarding > Workflow',
      '/onboarding',
      'app/onboarding/components/screens/workflow-screen.tsx',
      'Shows how the app connects projects, units, paints, guides, themes, and sessions into one workflow.',
      'Workflow onboarding step',
      'workflow screen',
      'The workflow carousel and navigation controls',
      'top',
      1540,
      array['onboarding', 'workflow']
    ),
    (
      'onboarding.first_project',
      'First project setup',
      'form',
      'Onboarding > First Project',
      '/onboarding',
      'app/onboarding/components/screens/first-project-screen.tsx',
      'Creates an optional starter project or first unit context to make the dashboard immediately useful.',
      'First project onboarding step',
      'first project screen',
      'The first project setup form',
      'top',
      1550,
      array['onboarding', 'projects', 'units']
    ),
    (
      'onboarding.guide_creation',
      'First guide setup',
      'form',
      'Onboarding > Guide Creation',
      '/onboarding',
      'app/onboarding/components/screens/guide-creation-screen.tsx',
      'Creates an optional starter guide so content-focused users begin with a saved guide draft.',
      'Guide onboarding step',
      'guide creation screen',
      'The first guide setup form',
      'top',
      1560,
      array['onboarding', 'guides']
    ),
    (
      'login.page',
      'Login',
      'page',
      'Login',
      '/login',
      'app/login/page.tsx',
      'Handles sign in, account creation, passwordless or credential entry, and Google authentication.',
      'Login page',
      'login experience',
      'The whole login viewport',
      'auto',
      1600,
      array['auth', 'login']
    ),
    (
      'login.google',
      'Google login',
      'button',
      'Login > Continue with Google',
      '/login',
      'app/login/google-login-button.tsx',
      'Starts Google OAuth sign-in and then returns the user to the app.',
      'Login form',
      'google login button',
      'The Continue with Google button',
      'top',
      1610,
      array['auth', 'login', 'google']
    ),
    (
      'settings.page',
      'Settings',
      'page',
      'Settings',
      '/settings',
      'app/settings/page.tsx',
      'Manages profile, avatar, display preferences, support routes, account actions, session controls, and legal links.',
      'Settings page',
      'settings page content',
      'The whole settings viewport',
      'auto',
      1700,
      array['settings', 'page']
    ),
    (
      'settings.profile',
      'Profile editor',
      'form',
      'Settings > Profile',
      '/settings',
      'app/settings/settings-profile-editor.tsx',
      'Updates public profile fields such as display name, avatar, and profile details used around the app.',
      'Settings profile section',
      'settings profile editor',
      'The profile editor fields',
      'top',
      1710,
      array['settings', 'profile']
    ),
    (
      'settings.preferences',
      'Preferences',
      'setting',
      'Settings > Preferences',
      '/settings',
      'app/settings/settings-preferences-section.tsx',
      'Stores user-level app preferences and display choices.',
      'Settings preferences section',
      'settings preferences section',
      'The preferences controls',
      'top',
      1720,
      array['settings', 'preferences']
    ),
    (
      'settings.session',
      'Session controls',
      'setting',
      'Settings > Session',
      '/settings',
      'app/settings/settings-session-section.tsx',
      'Shows sign-in/session status and provides sign out or session-related controls.',
      'Settings session section',
      'settings session section',
      'The session control buttons',
      'top',
      1730,
      array['settings', 'session', 'auth']
    ),
    (
      'settings.account',
      'Account controls',
      'setting',
      'Settings > Account',
      '/settings',
      'app/settings/settings-account-section.tsx',
      'Contains account-level actions and destructive controls that affect the user account.',
      'Settings account section',
      'settings account section',
      'The account control buttons',
      'top',
      1740,
      array['settings', 'account']
    ),
    (
      'support.page',
      'Support',
      'page',
      'Support',
      '/support',
      'app/support/page.tsx',
      'Explains ways to support Obsidian Gallery and provides feedback or help routes.',
      'Support page',
      'support page content',
      'The whole support viewport',
      'auto',
      1800,
      array['support', 'page']
    ),
    (
      'support.feedback',
      'Feedback card',
      'form',
      'Support > Feedback',
      '/support',
      'app/support/feedback-card.tsx',
      'Lets the user send feedback, bugs, or help requests from inside the app.',
      'Support page feedback area',
      'feedback card',
      'The feedback form/card',
      'top',
      1810,
      array['support', 'feedback']
    ),
    (
      'social.like',
      'Like content',
      'toggle',
      'Content action row > Like',
      '/recipes/[id]',
      'app/components/social/content-action-row.tsx',
      'Likes or unlikes shared content such as guides, units, themes, or other social surfaces.',
      'Public content action row',
      'button aria-label Like content type',
      'The like button in a content action row',
      'top',
      1900,
      array['social', 'like']
    ),
    (
      'social.save',
      'Save content',
      'toggle',
      'Content action row > Save',
      '/recipes/[id]',
      'app/components/social/content-action-row.tsx',
      'Saves or unsaves shared content for later use or reference.',
      'Public content action row',
      'button aria-label Save content type',
      'The save button in a content action row',
      'top',
      1910,
      array['social', 'save']
    ),
    (
      'social.report',
      'Report content',
      'modal',
      'Content action row > Report',
      '/recipes/[id]',
      'app/components/social/report-dialog.tsx',
      'Opens a report dialog so the user can flag content that needs review.',
      'Public content action row',
      'report dialog',
      'The report button and report dialog',
      'top',
      1920,
      array['social', 'report', 'moderation']
    ),
    (
      'images.color_sampler',
      'Image color sampler',
      'modal',
      'Image controls > Sample color',
      '/themes/[id]',
      'components/color-sampler/ColorSamplerDialog.tsx',
      'Lets the user sample a color from an uploaded image and use that color for matching paints or palette work.',
      'Image interaction modal',
      'color sampler dialog',
      'The image sampling canvas and toolbar',
      'auto',
      1930,
      array['images', 'color-sampler', 'paints']
    ),
    (
      'images.zoomable_gallery',
      'Zoomable gallery image',
      'modal',
      'Gallery > Expand image',
      '/projects/[id]',
      'app/components/gallery/zoomable-gallery-image.tsx',
      'Opens a larger inspectable gallery image for project, unit, guide, or theme images.',
      'Gallery modal layer',
      'zoomable gallery image',
      'The expanded gallery image viewer',
      'auto',
      1940,
      array['images', 'gallery', 'zoom']
    ),
    (
      'offline.page',
      'Offline page',
      'page',
      'Offline',
      '/offline',
      'app/offline/page.tsx',
      'Shows an offline fallback and tells the user to reconnect to pick up current projects, guides, paints, and progress.',
      'Offline fallback page',
      'offline page content',
      'The whole offline viewport',
      'auto',
      1950,
      array['offline', 'pwa']
    )
)
insert into public.feature_guide (
  uid,
  feature_name,
  feature_type,
  location_reference,
  page_path,
  component_reference,
  explanation,
  place_in_page,
  coach_mark_target,
  coach_mark_area,
  popup_placement,
  display_order,
  tags
)
select
  uid,
  feature_name,
  feature_type,
  location_reference,
  page_path,
  component_reference,
  explanation,
  place_in_page,
  coach_mark_target,
  coach_mark_area,
  popup_placement,
  display_order,
  tags
from seed
on conflict (uid) do update
set
  feature_name = excluded.feature_name,
  feature_type = excluded.feature_type,
  location_reference = excluded.location_reference,
  page_path = excluded.page_path,
  component_reference = excluded.component_reference,
  explanation = excluded.explanation,
  place_in_page = excluded.place_in_page,
  coach_mark_target = excluded.coach_mark_target,
  coach_mark_area = excluded.coach_mark_area,
  popup_placement = excluded.popup_placement,
  display_order = excluded.display_order,
  tags = excluded.tags,
  updated_at = now();
